# **행렬**

In [14]:
import numpy as np

e1 = np.array([[3,18,7,55],
               [44,7,13,32]])

e2 = np.array([[3,18,7,55],[44,7,13,32]])

print(f'e1 : {e1.shape} 행렬')

print('e1')
print(e1)

print('-------------------------------------')

print(f'e2 : {e2.shape} 행렬')

print('e2')
print(e2)

e1 : (2, 4) 행렬
e1
[[ 3 18  7 55]
 [44  7 13 32]]
-------------------------------------
e2 : (2, 4) 행렬
e2
[[ 3 18  7 55]
 [44  7 13 32]]


**np.array** : 행렬을 제작하는 함수라고 생각하면 된다. <br>
**(variable name).shape : 해당 행렬의 m x n 행렬 을 알려주는 함수라고 생각하면 된다
<br>

이때 줄 바꿈이 귀찮거나 불편하다면 좋은 소식이 있다. <br>
중간에 **,** 만 제대로 하고, 한 줄로 작성하여도 동일한 결과가 나온다.(e2) <br>
그럼 왜 굳이 **줄바꿈** 을 해야할까?

<br>

이유는 딱 하나다. **가독성** 실제 수학에서 행렬은 기본적으로 제 1행, 제 2행.... 제 n행 까지 나아가는 상황 이기에 <br>
손으로 계산하다가 파이썬으로 옮기는 과정에서 실수를 방지하고자 미연에 해둔 대처라고 볼 수 있다.

# 행렬의 연산

In [22]:
k = int(input('실수 k 입력'))
# k = 3이라 가정

A = np.array([[15,23],[19,51]])
B = np.array([[30,47],[24,35]])

sum = A + B
min = A - B
sq = A * B
ksq_a = k * A
ksq_b = k * B

print(f'행렬의 덧셈 : \n {sum}')
print('---------------------------------')
print(f'행렬의 뺄셈 : \n {min}')
print('---------------------------------')
print(f'행렬의 곱셈 : \n {sq}')
print('---------------------------------')
print(f'행렬의 실수배_A : \n {ksq_a}')
print('---------------------------------')
print(f'행렬의 실수배_B : \n {ksq_b}')


행렬의 덧셈 : 
 [[45 70]
 [43 86]]
---------------------------------
행렬의 뺄셈 : 
 [[-15 -24]
 [ -5  16]]
---------------------------------
행렬의 곱셈 : 
 [[ 450 1081]
 [ 456 1785]]
---------------------------------
행렬의 실수배_A : 
 [[ 45  69]
 [ 57 153]]
---------------------------------
행렬의 실수배_B : 
 [[ 90 141]
 [ 72 105]]
